name: exam_app
description: تطبيق اختبارات تفاعلي مع تحقق ذكاء اصطناعي
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.4
  syncfusion_flutter_pdf: ^27.2.5
  signature: ^5.5.0
  image_picker: ^1.1.2
  http: ^1.2.2
  dio: ^5.7.0
  provider: ^6.1.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
